#cloud-config
hostname: ${hostname}
local-hostname: ${hostname}
fqdn: ${hostname}.${dns_domain}
manage_etc_hosts: true

packages:
  - qemu-guest-agent

# Make sure qemu-guest-agent is running
runcmd:
  - systemctl start qemu-guest-agent
    
timezone: Europe/Helsinki

users:
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa ${sshpubkey_ansible}

final_message: "virtual machine deployment information : ${cloud-init_deployment_info}"
