---
- name: Debian - Disable IPv6 permanently after reboot in Sysctl config
  ansible.builtin.copy:
    dest: /etc/sysctl.d/no_ipv6.conf
    content: |
      net.ipv6.conf.all.disable_ipv6=1
      net.ipv6.conf.default.disable_ipv6=1
      net.ipv6.conf.lo.disable_ipv6=1
  register: no_ipv6_systcl_config
  become: true
...