---
all:
  hosts:
  children:
    jenkins:
      hosts:
        jenkins_1:
          ansible_host: 192.168.0.61
        jenkins_2:
          ansible_host: 192.168.0.62
    fileserver:
      hosts:
        fileserver_1:
          ansible_host: 192.168.0.63
        fileserver_2:
          ansible_host: 192.168.0.64
    nfs_server:
      vars:
        ansible_ssh_timeout: 30
      hosts:
        nfs_server_1:
          ansible_host: 192.168.0.71
        nfs_server_2:
          ansible_host: 192.168.0.72
    dns_ext:
      hosts:
        dns_ext_1:
          ansible_host: 192.168.0.5
    dolibarr:
      hosts:
        dolibarr_1:
          ansible_host: 192.168.0.80
    grocy:
      hosts:
        grocy_1:
          ansible_host: 192.168.0.81
    nfs_common:
      hosts:
        nfs_server_1:
        nfs_server_2:
        jenkins_1:
        jenkins_2:
        dolibarr_1:
        grocy_1:
...