---
- name: Include Docker Install playbook
  ansible.builtin.import_playbook: docker.yml

- name: Configure Debian VM with dockerized Jenkins, 1 server and 1 agent (Ansible and Opentofu)
  hosts: "{{ host }}"
  remote_user: jenkins
  become: true

  tasks:
    - name: CIFS mount - Create /home/jenkins/.cifs directory
      ansible.builtin.file: 
        path: "/home/jenkins/.cifs"
        owner: jenkins
        group: jenkins
        state: directory
        mode: '0700'

    - name: CIFS mount - Copy credentials file
      ansible.builtin.copy:
        src: /run/secrets/cifs_credentials
        dest: /home/jenkins/.cifs/credentials
        owner: jenkins
        group: jenkins
        mode: '0600'

    - name: CIFS mount - Mount needed datas for container on host
      ansible.posix.mount:
        src: "{{ data_source }}"
        path: "{{ data_mountpoint }}"
        opts: "rw,credentials=/home/jenkins/.cifs/credentials,uid=1000,gid=100"
        state: mounted
        fstype: cifs

    - name: CIFS mount - Copy ssh private keys file locally
      ansible.builtin.copy:
        src: "{{ data_mountpoint }}/sshkeys/{{ item }}"
        remote_src: true
        dest: /home/jenkins/.ssh/{{ item }}
        owner: jenkins
        group: jenkins
        mode: '0600'
      loop:
        - jenkins_agent_key
        - jenkins_server_key

    - name: Jenkins - Test plugin site is reachable
      ansible.builtin.uri:
        url: https://updates.jenkins.io/update-center.json
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 12
      delay: 5
      register: uri_output
      
    - name: Docker/Jenkins - Create docker-compose file
      ansible.builtin.template:
        src: ./templates/docker-compose.yml.j2
        dest: "{{ data_mountpoint }}/docker-compose-{{ inventory_hostname }}.yml"
        lstrip_blocks: yes

    - name: Docker/Jenkins - Build images and Deploy containers
      community.docker.docker_compose_v2:
        project_src: "{{ data_mountpoint }}"
        files:
          - "{{ data_mountpoint }}/docker-compose-{{ inventory_hostname }}.yml"
        build: always
        remove_orphans: true
      register: jenkins_service_build_deploy

    - name: Docker/Jenkins - Check build and deployment result
      debug: msg="{{ jenkins_service_build_deploy.stdout_lines }}"

    - name: Jenkins server - Wait until HTTP status is 200
      uri:
        url: "http://{{ ansible_host }}:8080/login"
        validate_certs: no
        status_code:
          - 200
      until: uri_output.status == 200
      retries: 12
      delay: 5
      register: uri_output
      
    - name: Jenkins server - Download jenkins-cli.jar in container
      community.docker.docker_container_exec:
        container: "{{ cicd_server.service_name }}"
        command: curl -o /tmp/jenkins-cli.jar http://{{ ansible_host }}:8080/jnlpJars/jenkins-cli.jar

    - name: Jenkins server - Reload server configuration from cli in container
      community.docker.docker_container_exec:
        container: "{{ cicd_server.service_name }}"
        command: java -jar /tmp/jenkins-cli.jar -s http://{{ ansible_host }}:8080/ -auth "admin:password" reload-jcasc-configuration
      register: jenkins_config_reload
...
