---
ansible_python_interpreter: auto_silent

ansible_user: "jenkins"

ansible_ssh_private_key_file: "/run/secrets/jenkins_agent_private_ssh_key"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

#data_mountpoint: "/srv/cifs"
data_local_path: "/srv/nfs"
nfs_server_vip: "192.168.0.73/24"
...