---
###
# SAMBA
###
data_source: "/srv/datadisk"
vrrp_vip: "192.168.0.65/24"

#pdbedit -L -w to see hash
#pdbedit -a user to set password
# https://www.browserling.com/tools/ntlm-hash
users_account:
- name: 'nas_user'
  groups: ''
  passwd_hash: ''
  uid: 1001
- name: 'ludovic'
  groups: 'DocLudoRW, DocStephRO, DocCommunRW, ApplicationsRW, MusiquesRW, PhotosRW, TelechargementsRW, VideosRW, InformatiqueRW'
  passwd_hash: ''
  uid: 1002
- name: 'stephanie'
  groups: 'DocLudoRO, DocStephRW, DocCommunRW, ApplicationsRW, MusiquesRW, PhotosRW, TelechargementsRW, VideosRW, InformatiqueRW'
  uid: 1003
  passwd_hash: ''
- name: 'photo_user'
  groups: 'PhotosRW'
  passwd_hash: ''
  uid: 1004
- name: 'music_user'
  groups: 'MusiquesRW'
  passwd_hash: ''
  uid: 1005
- name: 'media_user'
  groups: 'MusiquesRO, PhotosRO, VideosRO'
  passwd_hash: ''
  uid: 1006
- name: 'download_user'
  groups: 'TelechargementsRW'
  passwd_hash: ''
  uid: 1007
- name: 'backup_user'
  groups: 'DocCommunRO, DocLudoRO, DocStephRO, ApplicationsRO, MusiquesRO, PhotosRO, TelechargementsRO, VideosRO, InformatiqueRO'
  passwd_hash: ''
  uid: 1008
- name: 'cicd_user'
  groups: 'InformatiqueRO'
  passwd_hash: ''
  uid: 1009

users_default_group: 'users'

gid:
  - name: "RW"
    base_value: 2000
  - name: "RO"
    base_value: 2100

users_groups:
  - name: DocLudo
    gid: 1
  - name: DocSteph
    gid: 2
  - name: DocCommun
    gid: 3
  - name: Applications
    gid: 4
  - name: Musiques
    gid: 5
  - name: Photos
    gid: 6
  - name: Telechargements
    gid: 7
  - name: Videos
    gid: 8
  - name: Informatique
    gid: 9

##
# Syncthing
##
synchronization:
  # https://hub.docker.com/r/syncthing/syncthing/tags
  version: "1.27.8"
  service_name: syncthing
  
services:
  - name: "{{ synchronization.service_name }}"
    image_name: "syncthing/syncthing:{{ synchronization.version }}"
    container_name: "{{ synchronization.service_name }}"
    volumes:
      - "{{ data_source }}/Informatique/Config/{{ inventory_hostname }}:/var/syncthing:rw"
      - "{{ data_source }}:{{ data_source }}:rw"
    ports:
      - "8384:8384" # Web UI
      - "22000:22000/tcp" # TCP file transfers
    environment_variables:
      - "PCAP=cap_chown,cap_fowner+ep"
      - "PUID=1001" # nas_user
      - "PGID=100" # users
...