---
###
# SAMBA
###
data_source: "/srv/datadisk"
config_source: "{{ data_source }}/Informatique/Config/samba"
vrrp_vip: "192.168.0.65/24"

users_account:
- uid: 1001
  name: "{{ vault_1001_user }}"
  groups: ""
  passwd_hash: "{{ vault_1001_passwd_nthash }}"
- uid: 1002
  name: "{{ vault_1002_user }}"
  groups: "DocLudoRW, DocStephRO, DocCommunRW, ApplicationsRW, MusiquesRW, PhotosRW, TelechargementsRW, VideosRW, InformatiqueRW"
  passwd_hash: "{{ vault_1002_passwd_nthash }}"
- uid: 1003
  name: "{{ vault_1003_user }}"
  groups: "DocLudoRO, DocStephRW, DocCommunRW, ApplicationsRW, MusiquesRW, PhotosRW, TelechargementsRW, VideosRW, InformatiqueRW"
  passwd_hash: "{{ vault_1003_passwd_nthash }}"
- uid: 1004
  name: "{{ vault_1004_user }}"
  groups: "PhotosRW"
  passwd_hash: "{{ vault_1004_passwd_nthash }}"
- uid: 1005
  name: "{{ vault_1005_user }}"
  groups: "MusiquesRW"
  passwd_hash: "{{ vault_1005_passwd_nthash }}"
- uid: 1006
  name: "{{ vault_1006_user }}"
  groups: "MusiquesRO, PhotosRO, VideosRO"
  passwd_hash: "{{ vault_1006_passwd_nthash }}"
- uid: 1007
  name: "{{ vault_1007_user }}"
  groups: "TelechargementsRW"
  passwd_hash: "{{ vault_1007_passwd_nthash }}"
- uid: 1008
  name: "{{ vault_1008_user }}"
  groups: "DocCommunRO, DocLudoRO, DocStephRO, ApplicationsRO, MusiquesRO, PhotosRO, TelechargementsRO, VideosRO, InformatiqueRO"
  passwd_hash: "{{ vault_1008_passwd_nthash }}"
- uid: 1009
  name: "{{ vault_1009_user }}"
  groups: "InformatiqueRO"
  passwd_hash: "{{ vault_1009_passwd_nthash }}"

users_default_group: "users"

gid:
  - name: "RW"
    base_value: 2000
  - name: "RO"
    base_value: 2100

users_groups:
  - name: DocLudo
    gid: 1
  - name: DocSteph
    gid: 2
  - name: DocCommun
    gid: 3
  - name: Applications
    gid: 4
  - name: Musiques
    gid: 5
  - name: Photos
    gid: 6
  - name: Telechargements
    gid: 7
  - name: Videos
    gid: 8
  - name: Informatique
    gid: 9

##
# synchronization between NAS: Syncthing
##
synchronization:
  # https://hub.docker.com/r/syncthing/syncthing/tags
  version: "1.27.8"
  service_name: syncthing

##
# NAS File Browser: Filebrowser
##
filebrowser:
  version: "v2.27.0"
  base: "alpine:3.20"
  service_name: filebrowser

services:
  - name: "{{ synchronization.service_name }}"
    image_name: "{{ synchronization.service_name }}/{{ synchronization.service_name }}:{{ synchronization.version }}"
    container_name: "{{ synchronization.service_name }}"
    volumes:
      - "{{ config_source }}/{{ synchronization.service_name }}_{{ inventory_hostname }}:/var/{{ synchronization.service_name }}:rw"
      - "{{ data_source }}:{{ data_source }}:rw"
    ports:
      - "8384:8384" # Web UI
      - "22000:22000/tcp" # TCP file transfers
    environment_variables:
      - "PCAP=cap_chown,cap_fowner+ep"
      - "PUID=1001" # nas_user
      - "PGID=100" # users

  - name: "{{ filebrowser.service_name }}"
    dockerfile: |-
      FROM {{ filebrowser.base }}

      USER root
      ARG FB_DATABASE=/database.db
      ARG FB_USER=root
      ARG PUID
      ARG UMASK
      ARG FB_IMPORT_CONF
      ARG FB_IMPORT_USER

      RUN apk add --update --no-cache ca-certificates mailcap curl jq; \
          curl -s https://raw.githubusercontent.com/filebrowser/filebrowser/master/healthcheck.sh > /healthcheck.sh; \
          chmod +x /healthcheck.sh; \
          curl -s https://raw.githubusercontent.com/filebrowser/filebrowser/master/docker_config.json > /.filebrowser.json; \
          wget -qO- https://github.com/filebrowser/filebrowser/releases/download/{{ filebrowser.version }}/linux-amd64-filebrowser.tar.gz | tar xzv filebrowser; \
          if [[ $${FB_USER} != "root" ]]; then adduser -D -H -u $${PUID} -G users $${FB_USER}; fi; \
          printf '%s\n' \
                 "#!/bin/sh" \
                 "if [[ -f $${FB_DATABASE} ]]; then" \
                 "  if ! /filebrowser -d $${FB_DATABASE} config cat; then" \
                 "    /filebrowser -d $${FB_DATABASE} config init" \
                 "  fi" \
                 "  /filebrowser -d $${FB_DATABASE} config import $${FB_IMPORT_CONF}" \
                 "  /filebrowser -d $${FB_DATABASE} users import $${FB_IMPORT_USER}" \
                 "fi" \
                 "umask $${UMASK:-022}" \
                 "/filebrowser -d $${FB_DATABASE}" \
                 > /entrypoint.sh; \

          chmod +x /entrypoint.sh; \
          chown $${FB_USER}:users /entrypoint.sh
      
      USER $${FB_USER}

      HEALTHCHECK --start-period=2s --interval=5s --timeout=3s CMD /healthcheck.sh || exit 1

      VOLUME /srv
      EXPOSE 80

      ENTRYPOINT /entrypoint.sh
    image_name: "lvsb/{{ filebrowser.service_name }}:{{ filebrowser.version }}"
    container_name: "{{ filebrowser.service_name }}"
    volumes:
      - "{{ data_source }}:/srv:rw"
      - "{{ config_source }}/{{ filebrowser.service_name }}/filebrowser.db:/filebrowser.db:rw"
      # - "{{ config_source }}/{{ filebrowser.service_name }}/.filebrowser.json:/.filebrowser.json:rw"
    ports:
      - "8080:80" # Web UI
    args:
      - "FB_DATABASE=/filebrowser.db"
      - "FB_USER=nas_user"
      - "PUID=1001"
      - "PGID=100"
      - "UMASK=002"
      - "FB_IMPORT_CONF=/srv/Informatique/Config/samba/filebrowser/filebrowser_conf.json"
      - "FB_IMPORT_USER=/srv/Informatique/Config/samba/filebrowser/filebrowser_user.json"
    # https://github.com/filebrowser/filebrowser/issues/3214
    # https://filebrowser.org/cli/filebrowser
    # entrypoint: /bin/ash
    # command: "-c '
    #   umask 002;
    #   apk add --no-cache sudo
    #   /filebrowser users ls;
    #   if [[ $? == 1 ]]; then /filebrowser config init; fi;
    #   /filebrowser users import /srv/Informatique/Config/samba/filebrowser/filebrowser_user.json;
    #   /filebrowser config import /srv/Informatique/Config/samba/filebrowser/filebrowser_config.json;
    #   /filebrowser;
    #   '"
    # https://github.com/filebrowser/filebrowser/issues/2053
    #user: 1001:100

      # /filebrowser cmds add after_copy \"chown 1001:100 $$DESTINATION\";
      # /filebrowser cmds add after_upload \"chmod 664 $FILE\";
      # /filebrowser cmds add after_upload \"chown 1001:100 $DESTINATION\";
      # /filebrowser cmds add after_save \"chmod 664 $FILE\";
      # /filebrowser cmds add after_save \"chown 1001:100 \\$DESTINATION\";

      # /filebrowser config set --auth.method=noauth 2>/dev/null;
      # /filebrowser users update admin --locale fr 2>/dev/null;
      # /filebrowser cmds add after_copy \"chmod 664 \"$$\"DESTINATION\";
      # /filebrowser cmds ls;
      # /filebrowser config export /srv/Informatique/Config/samba/filebrowser.json;
...
